"""AURA-Core native adaptive radiance reconstruction scaffold."""

from aura.asset import AuraAsset
from aura.assignment import RegionEvidence, choose_carrier
from aura.benchmark import (
    AblationConfig,
    BenchmarkCase,
    BenchmarkSuite,
    RayQueryExpectation,
    apply_ablation,
    default_benchmark_suite,
    native_demo_ray_query_expectations,
    run_ablation_benchmarks,
    run_core_reconstruction_benchmark,
    run_ray_query_correctness_benchmark,
    run_reference_benchmark,
)
from aura.carriers import CarrierKind, CarrierSpec, default_registry
from aura.carrier_payloads import (
    BetaKernelPayload,
    GaborFrequencyPayload,
    GaussianFallbackPayload,
    NeuralResidualPayload,
    SemanticFeaturePayload,
    SurfaceCellPayload,
    VolumeCellPayload,
)
from aura.core import (
    CarrierEvolutionDecision,
    FramePrediction,
    ReconstructionConfig,
    ReconstructionReport,
    ReconstructionResult,
    ReconstructionStep,
    TrainingFrame,
    TrainingDataset,
    TrainingRegion,
    load_training_dataset,
    load_training_frames,
    reconstruct_demo_scene,
    synthetic_training_frames,
    synthetic_training_dataset,
    synthetic_training_regions,
    validate_training_dataset_document,
    write_synthetic_training_frames,
)
from aura.decomposition import EvidenceSample, decompose_evidence
from aura.elements import AuraChunk, AuraElement, Bounds
from aura.ingest import (
    BaselineExport,
    DepthEvidencePoint,
    GaussianSplatSample,
    IngestAdapterSpec,
    SemanticMaskRegion,
    SparsePointPrior,
    depth_points_to_evidence,
    discover_3dgs_export,
    load_3dgs_export,
    load_3dgs_ply,
    load_3dgs_scene,
    package_3dgs_export,
    semantic_masks_to_evidence,
    splats_to_scene,
    sparse_points_to_evidence,
    supported_ingest_adapters,
)
from aura.inspection import RayInspection, inspect_ray, inspect_scene_rays, native_demo_interaction_probes
from aura.migration import MigrationReport, migration_report
from aura.package import AuraPackage, load_package, package_scene, validate_package, validate_package_documents
from aura.ray import Ray, RayQueryResult
from aura.render import RenderImage, compare_images, image_mse, image_psnr, read_ppm, render_orthographic
from aura.schema import AURA_FORMAT, AURA_SCHEMA_VERSION, AURA_SUPPORTED_MAJOR_VERSIONS
from aura.scene import AuraScene
from aura.semantic import SemanticEdge, SemanticGraph, SemanticNode

__all__ = [
    "AuraChunk",
    "AuraElement",
    "AuraPackage",
    "AuraAsset",
    "AuraScene",
    "AblationConfig",
    "AURA_FORMAT",
    "AURA_SCHEMA_VERSION",
    "AURA_SUPPORTED_MAJOR_VERSIONS",
    "BaselineExport",
    "BenchmarkCase",
    "BenchmarkSuite",
    "BetaKernelPayload",
    "Bounds",
    "CarrierKind",
    "CarrierSpec",
    "CarrierEvolutionDecision",
    "DepthEvidencePoint",
    "EvidenceSample",
    "FramePrediction",
    "GaborFrequencyPayload",
    "GaussianFallbackPayload",
    "GaussianSplatSample",
    "IngestAdapterSpec",
    "NeuralResidualPayload",
    "MigrationReport",
    "Ray",
    "RayInspection",
    "RayQueryExpectation",
    "RayQueryResult",
    "RegionEvidence",
    "ReconstructionConfig",
    "ReconstructionReport",
    "ReconstructionResult",
    "ReconstructionStep",
    "RenderImage",
    "SemanticFeaturePayload",
    "SemanticEdge",
    "SemanticGraph",
    "SemanticNode",
    "SemanticMaskRegion",
    "SparsePointPrior",
    "SurfaceCellPayload",
    "TrainingFrame",
    "TrainingDataset",
    "TrainingRegion",
    "VolumeCellPayload",
    "apply_ablation",
    "choose_carrier",
    "compare_images",
    "depth_points_to_evidence",
    "decompose_evidence",
    "default_benchmark_suite",
    "default_registry",
    "discover_3dgs_export",
    "image_mse",
    "image_psnr",
    "load_3dgs_export",
    "load_3dgs_ply",
    "load_3dgs_scene",
    "load_package",
    "load_training_dataset",
    "load_training_frames",
    "migration_report",
    "native_demo_ray_query_expectations",
    "package_scene",
    "package_3dgs_export",
    "read_ppm",
    "render_orthographic",
    "reconstruct_demo_scene",
    "run_ablation_benchmarks",
    "run_core_reconstruction_benchmark",
    "run_ray_query_correctness_benchmark",
    "run_reference_benchmark",
    "inspect_ray",
    "inspect_scene_rays",
    "semantic_masks_to_evidence",
    "splats_to_scene",
    "sparse_points_to_evidence",
    "supported_ingest_adapters",
    "synthetic_training_frames",
    "synthetic_training_dataset",
    "synthetic_training_regions",
    "write_synthetic_training_frames",
    "native_demo_interaction_probes",
    "validate_package",
    "validate_package_documents",
    "validate_training_dataset_document",
]
